from om_memory.models import Message, Observation
from om_memory.storage.base import StorageBackend

class MongoDBStorage(StorageBackend):
    """
    MongoDB storage backend using motor.
    This is a stub implementation.
    """
    
    def __init__(self, connection_string: str = None):
        self.connection_string = connection_string
        raise NotImplementedError("MongoDBStorage is not yet fully implemented.")

    async def asave_messages(self, messages: list[Message]) -> None: ...
    def save_messages(self, messages: list[Message]) -> None: ...
    async def aget_messages(self, thread_id: str, limit: int = None) -> list[Message]: return []
    def get_messages(self, thread_id: str, limit: int = None) -> list[Message]: return []
    async def adelete_messages(self, message_ids: list[str]) -> None: ...
    def delete_messages(self, message_ids: list[str]) -> None: ...
    async def asave_observations(self, observations: list[Observation]) -> None: ...
    def save_observations(self, observations: list[Observation]) -> None: ...
    async def aget_observations(self, thread_id: str) -> list[Observation]: return []
    def get_observations(self, thread_id: str) -> list[Observation]: return []
    async def aupdate_observations(self, observations: list[Observation]) -> None: ...
    def update_observations(self, observations: list[Observation]) -> None: ...
    async def adelete_observations(self, observation_ids: list[str]) -> None: ...
    def delete_observations(self, observation_ids: list[str]) -> None: ...
    async def areplace_observations(self, thread_id: str, observations: list[Observation]) -> None: ...
    def replace_observations(self, thread_id: str, observations: list[Observation]) -> None: ...
    async def ainitialize(self) -> None: ...
    def initialize(self) -> None: ...
    async def aclose(self) -> None: ...
    def close(self) -> None: ...
